### ISSUE TITLE
Issue: Export

### ISSUE THREAD

**Issue by Sebio1980** [Fr75s/bigscraperqt#8]
Hello,

i have this issue when i export the scrap for my game.

```
[O] Hiding Game Bar
[O] Downloading Video
[D] Download Successful, Writing to file
[D] Writing Metadata to File
[O] Scraping Complete. Exiting...
[O] Exiting...
[W] Input Error: No gamepad found.
[W] Input Error: No gamepad found.
[U] Selected Folder (file:///recalbox/share/roms/n64)
[W] Input Error: No gamepad found.
[W] Input Error: No gamepad found.
[U] Selected System (Nintendo 64)
[U] Selected Export (EmulationStation)
-----
[I] Begin Task: Export
-----
[I] Data is ['file:///recalbox/share/roms/n64', 'Nintendo 64', 'EmulationStation']
[I] Will write to /recalbox/share/roms/n64
[O] Starting...
[I] Format: EmulationStation
[D] Reading Metadata File
[O] Exporting For EmulationStation...
[O] Showing Main Bar
[D] Copying Mario Party - Box - Front (Europe).png to folder
Traceback (most recent call last):
  File "/tmp/.mount_bigscrc2C9P0/usr/lib/python3.10/site-packages/bsqt/bsqt.py", line 79, in run
    self.t.run()
  File "/tmp/.mount_bigscrc2C9P0/usr/lib/python3.10/site-packages/bsqt/export.py", line 433, in run
    shutil.copyfile(os.path.join(paths["MEDIA"], system, game_form) + "/" + img + ".png", os.path.join(out_folder, "media", "boxFront") + "/" + img + ".png")
  File "/tmp/.mount_bigscrc2C9P0/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/recalbox/share/roms/n64/media/boxFront/Mario Party - Box - Front (Europe).png'
Aborted

```

Thank you for help

**Comment by Fr75s** [comment]
This issue should be fixed in bf49fd9. The issue here was that whenever data is being exported using the EmulationStation format, the proper directories aren't made, meaning the copied image files cannot exist, causing a crash.

This should fix exporting for EmulationStation.
